name: Publish on Tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get tag history

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rust-docs, rustfmt, clippy
          override: true

      - name: Build and Test
        run: |
          cargo build --release
          cargo test

      - name: Publish to Crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Get release information
        id: release_info
        run: |
          # Get exact tag name (vX.Y.Z)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Get rustc version
          RUSTC_VERSION=$(rustc -V)
          
          # Generate build date
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          
          # Create release body content
          RELEASE_BODY="Automated release
          Toolchain: $RUSTC_VERSION
          Build date: $BUILD_DATE"
          
          # Output for next steps
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_info.outputs.tag_name }}
          name: ${{ steps.release_info.outputs.tag_name }}  # Use tag as release name
          body: ${{ steps.release_info.outputs.release_body }}
          draft: false
          prerelease: false